script: |
  cd /home/ubuntu/online-clone-amazon

  # Pull latest code
  git pull origin main

  # Stop old container
  docker stop amazon-container || true
  docker rm amazon-container || true

  # Build new image
  docker build -t amazon-app .

  # Run new container
  docker run -d -p 80:80 --name amazon-container amazon-apptps://github.com/Ironhack-Archive/online-clone-amazon.git /tmp/app
            sudo mv /tmp/app/* .
            sudo rm -rf /tmp/app
            sudo systemctl restart nginx
